name: payu
description: Flutter package which gives a set of components for pay-by-link, one-time card payments, storing card options, scanning card data, and one-click payments (Google Pay, Apple Pay, BLIK).

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  payu_about: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_about
  payu_add_card: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_add_card
  payu_api: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_api
  payu_apple_pay: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_apple_pay
  payu_core: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_core
  payu_mastercard_installments: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_mastercard_installments
  payu_payment_methods: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_payment_methods
  payu_terms_and_conditions: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_terms_and_conditions
  payu_three_ds:
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_three_ds
  payu_translations: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_translations
  payu_web_payments:
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_web_payments

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.0.0
  flutter_lints: ^1.0.0

flutter:

import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - \/test\/*
