name: payu_state_management
description: Flutter package with Payu interface which allows to use wrapper over state management.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  payu_ui: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_ui

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0

flutter:

import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - \/test\/*