name: payu_mastercard_installments
description: Flutter package that allows Mastercard card holders to split payments into monthly installments

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  payu_about: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_about
  payu_state_management:
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_state_management
  payu_translations: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_translations
  payu_ui: 
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: release/0.0.1-alpha
      path: payu_ui
    
dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0
  mockito: ^5.1.0

flutter:

import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - \/test\/*