name: payu_mobile_payments_ios
description: A new flutter plugin project.

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  payu_mobile_payments_platform_interface:
    path: '../payu_mobile_payments_platform_interface'
    
dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PayuMobilePaymentsIosPlugin

import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - \/test\/*