name: payu_mobile_payments
description: A new flutter plugin project.

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  payu_mobile_payments_android:
    path: '../payu_mobile_payments_android'
  payu_mobile_payments_ios:
    path: '../payu_mobile_payments_ios'
  payu_mobile_payments_platform_interface:
    path: '../payu_mobile_payments_platform_interface'
    
dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: payu_mobile_payments_android
      ios:
        default_package: payu_mobile_payments_ios

