name: payu_add_card
description: Flutter package which allows to tokenize cards via Payu

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  
  payu_about: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_about
  payu_api: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_api
  payu_core: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_core
  payu_state_management: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_state_management
  payu_terms_and_conditions: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_terms_and_conditions
  payu_translations: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_translations
  payu_ui: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_ui

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: ^0.13.4
  mockito: ^5.1.0

flutter:

