name: payu_web_payments
description: Flutter package which allows to make Web payments via Payu

version: 1.0.0-beta.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  payu_api: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_api
  payu_core: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_core
  payu_state_management: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_state_management
  payu_translations: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_translations
  payu_ui: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
  webview_flutter: ^2.3.1
    
dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: ^0.13.4
  mockito: ^5.1.0

flutter:


