name: payu_three_ds
description: Flutter package which allows to handle Payu 3DS.

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  payu_api: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_api
  payu_core: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_core
  payu_state_management: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_state_management
  payu_translations: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      ref: feature/PUSDKM-694-google-pay
      path: payu_translations
  webview_flutter: ^2.3.1
    
dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.1.0


