name: payu_core
description: Flutter package with Payu core functionality and models.

version: 1.0.0-beta.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  payu_interface: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_interface
  url_launcher: ^6.0.15

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


