name: payu_apple_pay
description: Flutter package which allows make payments via Apple Pay

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0
  mockito: ^5.1.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PayuApplePayPlugin

import_sorter:
  emojis: false
  comments: false